# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to "/PROJECT_NAME" ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: "/x_ite"

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of "en".
lang: en


# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone:

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: X_ITE X3D Browser               # the main title
version: 8.5.2                         # x_ite latest version
x3d_latest_version: 8.5.2                # x3d latest version

tagline: Step Into The Future          # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  X_ITE X3D Browser, a framework for integrating and manipulating X3D and VRML scenes in HTML.

# fill in the protocol & hostname for your site, e.g., "https://username.github.io"
url: "https://create3000.github.io"

github:
  username: create3000/x_ite            # change to your github username

twitter:
  username: web3dconsortium             # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Holger Seelig
  email: holger.seelig@google.com         # change to your email address
  links:
    # The first element serves as the copyright owner"s link
    - https://twitter.com/web3dconsortium # change to your twitter homepage
    - https://github.com/create3000       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification:                 # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id:                 # fill in your Google Analytics ID
  # Google Analytics page views report settings
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: dark  # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts" images) paths starting with "/"
#
# e.g. "https://cdn.com"
img_cdn: ""

# the avatar on sidebar, support local or CORS resources
avatar: "assets/img/logo.png"

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active:         # The global switch for posts comments, e.g., "disqus".  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:              # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:           # optional, default to "pathname"
    input_position:    # optional, default to "bottom"
    lang:              # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:      # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is "true"
    env:          # [development|production]

pwa:
  enabled: true   # the option for PWA feature

paginate:

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: x_ite
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /:slugified_categories/:slug
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [x-development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

nav:
  main:
    - title: "Quick-Start Guide"
      children:
        - title: "Getting Started"
          url: /
        - title: "What's New"
          url: /what-s-new
        - title: "Features"
          url: /features
        - title: "Browser Support"
          url: /browser-support
        - title: "Supported Nodes"
          url: /supported-nodes
        - title: "Accessing the External Browser"
          url: /accessing-the-external-browser
        - title: "DOM Integration"
          url: /dom-integration
        - title: "Custom Shaders"
          url: /custom-shaders
        - title: "Setup a localhost Server"
          url: /setup-a-localhost-server
        - title: "How To Configure Your Web Server"
          url: /how-to-configure-your-web-server
        - title: "Glossary"
          url: /glossary
        - title: "Report a Bug"
          url: /report-a-bug
  reference:
    - title: "JavaScript Reference"
      children:
        - title: "Script Node Authoring Interface"
          url: /reference/script-node-authoring-interface
        - title: "ECMAScript Object and Function Definitions"
          url: /reference/ecmascript-object-and-function-definitions
        - title: "Browser Services"
          url: /reference/browser-services
        - title: "Scene Services"
          url: /reference/scene-services
        - title: "Field Services and Objects"
          url: /reference/field-services-and-objects
        - title: "Route Services"
          url: /reference/route-services
        - title: "Prototype Services"
          url: /reference/prototype-services
        - title: "Constants Services"
          url: /reference/constants-services
  tutorials-basic:
    - title: "Basic Tutorials"
      children:
        - title: "Hello, World!"
          url: /tutorials/hello-world
        - title: "Basic Nodes"
          url: /tutorials/basic-nodes
  tutorials-shapes-geometry-and-appearance:
    - title: "Shapes, Geometry, and Appearance"
      children:
        - title: "Introducing X3D"
          url: /tutorials/introducing-x3d
        - title: "Building a X3D World"
          url: /tutorials/building-a-x3d-world
        - title: "Building Primitive Shapes"
          url: /tutorials/building-primitive-shapes
        - title: "Transforming Shapes"
          url: /tutorials/transforming-shapes
        - title: "Controlling Appearance with Materials"
          url: /tutorials/controlling-appearance-with-materials
        - title: "Grouping Nodes"
          url: /tutorials/grouping-nodes
        - title: "Naming Nodes"
          url: /tutorials/naming-nodes
  tutorials-animation-sensors-and-geometry:
    - title: "Animation, Sensors, and Geometry"
      children:
        - title: "Introducing Animation"
          url: /tutorials/introducing-animation
        - title: "Animating Transforms"
          url: /tutorials/animating-transforms
        - title: "Sensing Viewer Actions"
          url: /tutorials/sensing-viewer-actions
        - title: "Building Shapes out of Points, Lines, and Faces"
          url: /tutorials/building-shapes-out-of-points-lines-and-faces
        - title: "Building Elevation Grids"
          url: /tutorials/building-elevation-grids
        - title: "Building Extruded Shapes"
          url: /tutorials/building-extruded-shapes
        - title: "Controlling Color on Coordinate-Based Geometry"
          url: /tutorials/controlling-color-on-coordinate-based-geometry
        - title: "Controlling Shading on Coordinate-Based Geometry"
          url: /tutorials/controlling-shading-on-coordinate-based-geometry
  tutorials-textures-lights-and-environment:
    - title: "Textures, Lights, and Environment"
      children:
        - title: "Mapping Textures"
          url: /tutorials/mapping-textures
        - title: "Controlling How Textures are Mapped"
          url: /tutorials/controlling-how-textures-are-mapped
        - title: "Lighting Your World"
          url: /tutorials/lighting-your-world
        - title: "Adding Backgrounds"
          url: /tutorials/adding-backgrounds
        - title: "Adding Fog"
          url: /tutorials/adding-fog
        - title: "Adding Sound"
          url: /tutorials/adding-sound
        - title: "Controlling the Viewpoint"
          url: /tutorials/controlling-the-viewpoint
        - title: "Controlling Navigation"
          url: /tutorials/controlling-navigation
        - title: "Sensing the Viewer"
          url: /tutorials/sensing-the-viewer
  tutorials-scripts-and-prototypes:
    - title: "Scripts and Prototypes"
      children:
        - title: "Controlling Detail"
          url: /tutorials/controlling-detail
        - title: "Introducing Script Use"
          url: /tutorials/introducing-script-use
        - title: "Writing Program Scripts with ECMAScript"
          url: /tutorials/writing-program-scripts-with-ecmascript
        - title: "Creating New Node Types"
          url: /tutorials/creating-new-node-types
        - title: "Providing Information About Your World"
          url: /tutorials/providing-information-about-your-world
  tutorials-optimize-your-scene:
    - title: "Optimize Your Scene"
      children:
        - title: "Improving Performance"
          url: /tutorials/improving-performance
        - title: "Increasing Rendering Speed"
          url: /tutorials/increasing-rendering-speed
